blueprint: page

title: Les diffusions d'événements

icon: ticket

options:
  sort: false
  changeSlug: false
  delete: false
  changeTitle: false
  changeStatus: false
  duplicate: false

columns:
  - width: 1/1
    fields:
      htmlContent:
        type: blocks
        label: Contenu
        fieldsets:
          - textWithTitle
          - image
          - video
          - imageGallery
          - link
          - quote
  - width: 1/1
    sections:
      pages:
        label: Pages
        type: pages
        layout: cards
        image:
          icon: false
          back: white
        template:
          - diffusion__subpage
