blueprint: page

title: Informations de la billetterie Infomaniak

num: date

icon: 📖

options:
  sort: false
  delete: false
  changeSlug: false
  changeTitle: false
  changeStatus: false
  duplicate: false

status:
  draft:
    label: Brouillon
    text: Ne peut être vue que par les éditeurs ayant accès à l'administration.
  listed:
    label: Publié
    text: en ligne.

columns:
  - width: 1/1
    fields:
      shop:
        type: url
        label: Lien billetterie de saison
      subscription_link:
        type: url
        label: Lien vers l'abonnement de saison
      subscription_text:
        type: text
        label: Texte bouton vers l'abonnement de saison
