blueprint: page

title: Page simple

icon: page

options:
  sort: true
  changeSlug: true
#  delete: false
  changeTitle: true
  changeStatus: true
  duplicate: true

columns:
  - width: 1/1
    fields:
      showInCalendar:
        label: Afficher dans le programme
        type: toggle
        width: 3/6

      dateStart:
        width: 1/6
        required: false
        label: Date de début
        type: date
        default: now
        when:
          showInCalendar: true

      dateEnd:
        width: 1/6
        required: false
        label: Date de fin
        type: date
        default: now
        when:
          showInCalendar: true


      gapCol_01:
        type: gap
        width: 1/6

      gapCol:
        type: gap
        width: 1/2
      showInNavigation:
        label: Afficher dans la navigation
        width: 1/4
        type: toggle
        default: false
      showInHome:
        label: Afficher dans sur la home
        width: 1/4
        type: toggle
        default: false
      content:
        type: blocks
        label: Contenu
        fieldsets:
          - section-block-content
          - section-block-link-to-event
  - width: 1/1
    sections:
      sectionsInfoDetails:
        label: ' '
        type: info
        theme: none
        text: |
          ### sous-page(s)
      drafts:
        extends: sections/page-simple
        type: pages
        label: Brouillon
        status: draft
        layout: list
      listed:
        extends: sections/page-simple
        type: pages
        label: Publié
        status: listed
        search: true
