blueprint: page

title: Sous page

icon: page

options:
  sort: true
  changeSlug: true
#  delete: false
  changeTitle: true
  changeStatus: true
  duplicate: true

columns:
  - width: 1/1
    fields:
      templateWith_3_coll:
        label: Temple avec 3 colonnes
        type: toggle
        width: 1/4
      gapCol:
        type: gap
        width: 1/4
      showInNavigation:
        label: Afficher dans la navigation
        width: 1/4
        type: toggle
        default: false
      showInHome:
        label: Afficher dans sur la home
        width: 1/4
        type: toggle
        default: false
      content:
        type: blocks
        label: Contenu
        fieldsets:
          - section-block-content
          - section-block-link-to-event
