blueprint: page

title: Page simple

icon: page

options:
  sort: true
  changeSlug: true
#  delete: false
  changeTitle: true
  changeStatus: true
  duplicate: true

columns:
  - width: 1/1
    fields:
      gapCol:
        type: gap
        width: 1/2
      showInNavigation:
        width: 1/4
        type: toggle
        default: false
      showInHome:
        width: 1/4
        type: toggle
        default: false
      htmlContent:
        width: 1/2
        type: blocks
        label: Contenu
        fieldsets:
          - textWithTitle
          - image
          - video
          - imageGallery
      htmlContent_falk:
        width: 1/2
        type: blocks
        label: Contenu FALK
        fieldsets:
          - text
          - image
          - video
          - imageGallery

  - width: 1/1
    sections:
      sectionsInfoDetails:
        label: ' '
        type: info
        theme: none
        text: |
          ### sous-page(s)
      drafts:
        extends: sections/page-simple
        type: pages
        label: Brouillon
        status: draft
        layout: list
      listed:
        extends: sections/page-simple
        type: pages
        label: Publié
        status: listed
        search: true
