blueprint: page

title: Project

num: '{{ page.dateEnd.toDate("Ymd") }}'

icon: 📖

options:
  delete:
    admin: true
    reader: false

status:
  draft:
    label: Brouillon
    text: Le spectacle est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès à l'administration.
  listed:
    label: Publié
    text: Le spectacle est en ligne.

columns:

  - width: 3/4
    fields:
      subtitle:
        type: text
        label: Sous-titre
        width: 3/4

  - width: 3/4
    fields:
      title_media:
        label: 🔷 Medias
        type: headline

      cover:
        type: files
        required: true
        label: Image de couverture
        help: Image de couverture à gauche
        extends: files/imageOnlyOne
        width: 1/3
        layout: cards
        image:
          back: white

      cover_gap:
        type: gap
        width: 2/3

      gallery:
        type: files
        label: Galerie
        help: Galerie d'image sur la gauche
        extends: files/imageMulti
        width: 1/2
        layout: cardlets
        image:
          back: black

      youtube_links:
        label: Liste lien YouTube
        type: structure
        width: 1/2
        fields:
          link_url:
            label: URL
            type: url
            required: true

  - width: 1/4
    fields:
      title_params:
        label: 🟨 Paramètres
        type: headline
      showInHome:
        label: Afficher dans sur la home
        width: 1/4
        type: toggle
        default: false

  - width: 3/4
    fields:
      gap_tickets:
        type: gap
        width: 1/1
      title_tickets:
        label: 🚀 Billetterie
        type: headline
      externalTicketServiceLink:
        label: Lien pour la billetterie
        type: link
        width: 1/2
        options:
          - url
      externalTicketServiceName:
        label: Texte pour le lien de la billetterie
        type: text
        width: 1/2

  - width: 3/4
    fields:
      gap_infos:
        type: gap
        width: 1/1
      title_infos:
        label: 🟣 Informations
        type: headline
      season:
        label: Saison
        type: select
        required: true
        width: 1/2
        options:
          type: query
          query: site.find('saisons').childrenAndDrafts.template('season')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"
      isCover:
        label: Reprise
        type: toggle
        width: 1/2
      places:
        label: salle(s)
        type: multiselect
        width: 1/2
        options:
          type: query
          query: site.find('places').childrenAndDrafts.template('place')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"
      eventInfo:
        width: 3/4
        label: Informations pour la vignette du spectacle
        type: text
        help: Text repris pour la vignette d'événement seulement (ne ré-apparait pas dans le contenu de la page)

      company:
        width: 3/4
        label: Compagnie(s) / Mise en scène
        type: structure
        fields:
          authors_name:
            label: nom
            type: text
          authors_link:
            label: liens externe
            type: url





  - width: 3/4
    fields:
      gap_dates:
        type: gap
        width: 1/1
      title_dates:
        type: headline
        label: 🌍 Dates et horaires

      dateStart:
        width: 1/2
        required: true
        label: Date de début
        type: date
        default: now

      dateEnd:
        width: 1/2
        required: true
        label: Date de fin
        type: date
        default: now

      list_of_dates:
        width: 3/4
        label: Liste des dates
        type: structure
        fields:
          list_of_dates_date:
            required: true
            label: Jour
            type: date
          list_of_dates_hour:
            label: Heure
            required: false
            type: time
            display: HH:mm
          list_of_dates_ticket_link:
            type: link
            label: lien vers la billetterie
            options:
              - url
          list_of_dates_is_relax:
            label: sortie relax?
            type: toggle

      htmlDetails:
        type: blocks
        label: Détails des dates et horaires
        width: 3/4
        empty: Informations sur la durée, avec ou sans entracte et les horaires. (voir informations en bleu)
        fieldsets:
          - text

      htmlDetails_info:
        type: info
        label: " "
        width: 1/4
        text: |
          Durée HHhMM, avec ou sans entracte





  - width: 1/1
    fields:
      gap_content:
        type: gap
        width: 1/1
      title_content:
        type: headline
        label: ❇️ Contenu

      htmlContent:
        width: 1/2
        type: blocks
        label: Contenu
        fieldsets:
          - text
          - image
          - video
          - imageGallery
          - link
          - quote
          - break

      htmlContent_falk:
        width: 1/2
        type: blocks
        label: Contenu FALC
        fieldsets:
          - text
          - image
          - video
          - imageGallery
          - link
          - quote
          - break
