blueprint: page

title: Project

#num: date

icon: 📖

status:
  draft:
    label: Brouillon
    text: Le spectacle est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès à l'administration.
  listed:
    label: Publié
    text: Le spectacle est en ligne.

columns:
  - width: 3/4
    fields:
      eventInfo:
        label: Informations pour la vignette du spectacle
        type: text
        help: Text repris pour la vignette d'événement seulement (ne ré-apparait pas dans le contenu de la page)

      externalTicketServiceLink:
        label: Lien pour la billetterie
        type: link
        width: 1/2
        options:
          - url
      externalTicketServiceName:
        label: Texte pour le lien de la billetterie
        type: text
        width: 1/2


  - width: 1/4
    fields:
      season:
        label: Saison
        type: select
        required: true
        options:
          type: query
          query: site.find('saisons').childrenAndDrafts.template('season')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"
      isCover:
        label: Reprise
        type: toggle
      showInHome:
        label: Afficher dans sur la home
        width: 1/4
        type: toggle
        default: false

  - width: 1/3
    fields:
      cover:
        type: files
        required: true
        label: Image de couverture
        help: Image de couverture
        extends: files/imageOnlyOne

  - width: 2/3
    fields:
      places:
        label: salle(s)
        type: multiselect
        options:
          type: query
          query: site.find('places').childrenAndDrafts.template('place')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"

  - width: 1/3
    fields:
      company:
        label: Compagnie(s) / Mise en scène / Texte(s)
        type: structure
        fields:
          authors_name:
            label: nom
            type: text
          authors_link:
            label: liens externe
            type: url
      linked_spectacle:
        label: Spectacle(s) lié(s)
        type: multiselect
        options:
          type: query
          query: site.find('spectacles').childrenAndDrafts.template('spectacle')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"

  - width: 2/3
    fields:
      peoples:
        label: Distribution
        type: writer
        marks:
          - italic
        nodes: false

  - width: 1/1
    fields:
      list_of_dates:
        label: Liste des dates
        type: structure
        fields:
          list_of_dates_date:
            required: true
            label: Jour
            type: date
          list_of_dates_hour:
            label: Heure
            required: false
            type: time
            display: HH:mm
          list_of_dates_ticket_link:
            type: link
            label: lien vers la billetterie
            options:
              - url
          list_of_dates_is_relax:
            label: sortie relax?
            type: toggle

      htmlDetails:
        type: blocks
        label: Détails des dates et horaires
        width: 3/4
        empty: Informations sur la durée, avec ou sans entracte et les horaires. (voir informations en bleu)
        fieldsets:
          - text
      htmlDetails_info:
        type: info
        label: " "
        width: 1/4
        text: |
          Durée HHhMM, avec ou sans entracte

          lundi-samedi à HHhMM, dimanche à HHMM.


      htmlContent:
        width: 1/2
        type: blocks
        label: Contenu
        fieldsets:
          - text
          - image
          - video
          - imageGallery
          - link
          - quote
          - break
      htmlContent_falk:
        width: 1/2
        type: blocks
        label: Contenu FALC
        fieldsets:
          - text
          - image
          - video
          - imageGallery
          - link
          - quote
          - break
      details:
        label: Production(s) / Coproduction(s) / Soutien(s)
        type: writer
        marks:
          - italic
        nodes: false
