blueprint: page

title: Project

num: date

icon: 📖

status:
  draft:
    label: Brouillon
    text: Le spectacle est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès à l'administration.
  listed:
    label: Publié
    text: Le spectacle est en ligne.

columns:
  - width: 3/4
    fields:
      eventTitle:
        label: Nom de l'événement dans la billeterie infomaniak
        type: multiselect
#        required: true
#        max: 1
        options:
          type: api
          url: "https://grutli.deno.dev/"
          text: "{{ item.name }}"
          value: "{{ item.name }}"

  - width: 1/4
    fields:
      isCover:
        label: Reprise
        type: toggle
  - width: 1/3
    fields:
      cover:
        type: files
        required: true
        label: Image de couverture
        help: Image de couverture
        extends: files/imageOnlyOne

  - width: 2/3
    fields:
      places:
        required: true
        label: salle(s)
        type: multiselect
        min: 1
        options:
          type: query
          query: site.find('places').childrenAndDrafts.template('place')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"

  - width: 1/3
    fields:
      company:
        label: Compagnie(s) / Mise en scène / Texte(s)
        type: structure
        fields:
          authors_name:
            label: nom
            type: text
          authors_link:
            label: liens externe
            type: url
      linked_spectacle:
        label: Spectacle(s) lié(s)
        type: multiselect
        options:
          type: query
          query: site.find('spectacles').childrenAndDrafts.template('spectacle')
          text: "{{ item.title }}"
          value: "{{ item.slug }}"

  - width: 2/3
    fields:
      peoples:
        label: Distribution
        type: structure
        columns:
          peoples_function:
            width: 1/2
          peoples_name:
            width: 1/2
        fields:
          peoples_function:
            label: fonction
            type: text
          peoples_name:
            label: nom
            type: text

  - width: 1/1
    fields:
      htmlContent:
        type: blocks
        label: Contenu
        fieldsets:
          - text
          - image
          - video
          - imageGallery
#          - type: heading
#            extends: blocks/heading
#            fields:
#              level:
#                options:
#                  - h2
#                  - h3
      details:
        label: liste détails (Marilu ?)
        type: structure
        fields:
          details_title:
            label: nom
            type: text
          details_items:
            type: structure
            fields:
              details_item_firstname:
                label: nom 1
                type: text
              details_item_lastname:
                label: nom 2
                type: text

#      galleryProject:
#        type: blocks
#        label: Galerie
#        fieldsets:
#          - image
      htmlDetails:
        type: blocks
        label: Détails (Marilu?)
        fieldsets:
          - text

#  - width: 1/3
#    sections:
#      meta:
#        type: fields
#        fields:

