blueprint: page

name: Section contenu
icon: text
wysiwyg: true
preview: fields

fields:
  titre:
    required: false
    type: writer
    inline: true
    marks:
      - italic
  htmlContent:
    required: true
    width: 1/2
    type: blocks
    label: Contenu
    fieldsets:
      - textWithTitle
      - image
      - video
      - imageGallery
      - link
      - quote
  htmlContent_falk:
    width: 1/2
    type: blocks
    label: Contenu FALC
    fieldsets:
      - textWithTitle
      - image
      - video
      - imageGallery
      - link
