blueprint: page

name: Section lien vers un événement
icon: text
wysiwyg: true
preview: fields

fields:
  linked_spectacle:
    required: true
    label: Spectacle(s)
    type: multiselect
    max: 1
    options:
      type: query
      query: site.find('spectacles').childrenAndDrafts.template('spectacle')
      text: "{{ item.title }}"
      value: "{{ item.slug }}"
