title: Site

columns:
  - width: 1/4
    sections:
      info:
        label: ' '
        type: info
        theme: none
        text: |
          ### Informations générales
      placeList:
        label: "Salles et lieux"
        type: pages
        status: listed
        image: false
        templates: places
        layout: cards
        size: medium
      infomaniakTicketInformation:
        label: "Informations liées à la billetterie infomaniak"
        type: pages
        status: listed
        image: false
        templates: infomaniak-tickets-informations
        layout: cards
        size: medium
  - width: 3/4
    sections:
      pages:
        label: Spectacles
        type: pages
        template:
          - spectacles
